### ISSUE TITLE
Pathing restricted to dev's file pathing

### ISSUE THREAD

**Issue by dinogomez** [nimbly-dev/nimbly-codeplayground#1]
![image](https://user-images.githubusercontent.com/41871666/88134483-51635580-cc17-11ea-9cbd-d4aa15d18499.png)
![image](https://user-images.githubusercontent.com/41871666/88134488-558f7300-cc17-11ea-8733-c138e69a61fc.png)

Pathing locked

**Comment by nimbly-dev** [comment]
Hotdog
